server:
  port: 8080

spring:
  application:
    name: ${project.artifactId}
  cache:
    type: redis
  redis:
    port: ${REDIS_PORT:6379}
    host: ${REDIS_HOST:192.168.1.108}
    password: ${REDIS_PASSWORD:123456}
    database: ${REDIS_DATABASE:0}
    lettuce:
      pool:
        max-idle: 10
        max-wait: 30
        min-idle: 0
        max-active: 200
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    druid:
      url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/cloud?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&amp&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai}
      username: ${MYSQL_USER_NAME:root}
      password: ${MYSQL_PASSWORD:123456}
      driver-class-name: com.mysql.cj.jdbc.Driver
      keep-alive: true
      async-init: true
      min-evictable-idle-time-millis: 600000
      # 连接闲置剔除时间
      time-between-eviction-runs-millis: 300000
      validation-query-timeout: 1
      validation-query: SELECT 1
      test-on-borrow: true
      max-pool-prepared-statement-per-connection-size: 100
      pool-prepared-statements: true
      max-active: 100
      initial-size: 30
      min-idle: 30
      max-wait: 60000
      # 必须大于 time-between-eviction-runs-millis 时间
      keep-alive-between-time-millis: 450000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true

logging:
  file:
    name: ./logs/${spring.application.name}.log

