package com.hf.biz.dao.entity;

import java.io.Serializable;
import java.sql.*;
import javax.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Entity(name = "com.hf.biz.dao.entity.IbCookInfo")
@Table(name = "ib_cook_info")
public class IbCookInfo implements Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private Long id;
  @Column(name = "\"create_time\"", nullable = true)
  private Timestamp createTime;
  @Column(name = "\"update_time\"", nullable = true)
  private Timestamp updateTime;
  @Column(name = "\"biz_id\"", nullable = true)
  private Long bizId;
  @Column(name = "\"class_id\"", nullable = true)
  private Long classId;
  @Column(name = "\"content\"", nullable = true)
  private String content;
  @Column(name = "\"cooking_time\"", nullable = true)
  private String cookingTime;
  @Column(name = "\"material\"", nullable = true)
  private String material;
  @Column(name = "\"name\"", nullable = true)
  private String name;
  @Column(name = "\"people_num\"", nullable = true)
  private String peopleNum;
  @Column(name = "\"pic\"", nullable = true)
  private String pic;
  @Column(name = "\"prepare_time\"", nullable = true)
  private String prepareTime;
  @Column(name = "\"process\"", nullable = true)
  private String process;
  @Column(name = "\"tag\"", nullable = true)
  private String tag;
}